### ISSUE TITLE
drupal s3 stored module

### ISSUE THREAD

**Issue by lastlink** [naderman/composer-aws#14]
I couldn't figure out from your documentation on how to require or setup packages.

Here is my composer.json

```
"installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module","type:composer-s3"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        },

{
            "type": "composer-s3",
            "url": "s3://urltofile.tar.gz" 
        }
```

I try to do a require 

`
composer require bundlename.tar.gz
`
And get this error

```
 [InvalidArgumentException]
  Could not find a matching version of package bundlename.tar.gz Check the package spelling, your version constraint and that the package is available in a stability which matches your
   minimum-stability (stable).
```

My config.json is configured properly in composer.json and I don't get the aws key error. Help would be appreciated and updating your readme.md.

**Comment by naderman** [comment]
You require packages with their name, not with a filename for a code archive. Please refer to the Composer documentation at https://getcomposer.org/doc/ on how to use Composer. This is merely a plugin to store a Composer repository, e.g. generated by Satis on S3. It's not a way to download individual files from S3 with Composer.
