### ISSUE TITLE
Cannot redeclare Aws\constantly

### ISSUE THREAD

**Issue by aftabnaveed** [naderman/composer-aws#15]
In my project, I have a local dependency on Amazon AWS SDK v3. When I installed the extension and try to run `composer update` I get this error:

`Cannot redeclare Aws\constantly() (previously declared in /srv/laravel/vendor/aws/aws-sdk-php/src/functions.php:19)`

I even tried to wrap it inside `function_exists` but it still did not work. It seems like the extension conflicts with already installed AWS SDK hence the error.

**Comment by aftabnaveed** [comment]
Looks like this Repo is dead!  This plugin does not work with `composer update` in local composer.json file.

**Comment by naderman** [comment]
Sorry, I don't have a use for this myself anymore, I'd be happy to let somebody else take over maintenance for this. I'll also happily merge PRs if they are sent to fix issues.

**Comment by naderman** [comment]
I belive this was fixed by @nielsdraaisma's PR
