### ISSUE TITLE
Does not work with create-project

### ISSUE THREAD

**Issue by logicalor** [naderman/composer-aws#19]
As per issue title, the plugin doesn't work with the create-project command.  This seems to be a limitation of Composer in that the [CreateProjectCommand class](https://github.com/composer/composer/blob/master/src/Composer/Command/CreateProjectCommand.php) doesn't provide a preDownload hook for the plugin to insert its s3 handling into.  Not sure if there is any workaround (other than to not use create-project!).

**Comment by naderman** [comment]
@logicalor good find! Don't use create project myself so never noticed. Can you report the missing hook as a bug on composer?

**Comment by logicalor** [comment]
Sure thing, I'm about halfway to a solution which involves updating Composer's CreateProjectCommand class to inject an EventDispatcher when instantiating repositories.  I'll update here once I submit a PR to the Composer project.

**Comment by logicalor** [comment]
My [PR with the fix for this issue](https://github.com/composer/composer/pull/9057) has been merged into the composer 1.10 roadmap branch, so I presume a release containing the fix will be published in the not-too-distant future :)
