### ISSUE TITLE
How do i implements it?

### ISSUE THREAD

**Issue by JJK801** [naderman/composer-aws#3]
Earlier today, we tried to implements your aws plugin into our composer application, but it didn't worked.

What we tried is:
- Add it as a project's composer.json requirement (like in the README file, IMO it got no sense because it must run before to look for repositories), so it didn't worked
- Add it globally using `composer global require "naderman/composer-aws:~0.2"`

Every time we run a `composer update` we get an error saying that s3 scheme is not implemented.

We really need this feature ASAP, can you help us?

Thanks

**Comment by aftabnaveed** [comment]
@JJK801  though this is 5 years old post, but it is still not wokring for me when I put the dependency in my local composer.json file. I am using version 1.0
