### ISSUE TITLE
Checksum validation fail

### ISSUE THREAD

**Issue by corvus-ch** [naderman/composer-aws#9]
Using satis, I have created a composer repository containing one single package. This I have uploaded to an s3 bucket which is publicly accessible over http (static webpage hosting). Using this repository is working as expected. 

Now I wanted to secure this repository by removing the static webpage hosting and using this composer extension. While it can read the repository meta data, composer install failed to verify the checksum of the downloaded checksum and does a fallback to the git source.

This implies, that the download process of this composer extensions seems to have some issues.

What information would be of help for resolving this issue?

**Comment by naderman** [comment]
can you paste the actual error you get from composer with `-vvv` for full debug output for a start?

**Comment by corvus-ch** [comment]
Hmm, interesting. I can no longer reproduce this issue. I am sorry for bothering.
